---
- name: Install Package
  hosts: "{{ inventory_hostname }}"
  vars: 
    package: from_playbook
    
  roles:
   - ansible-role-listvars

  tasks:
    
  - debug: var=drop_down
  
  - name: Install package
    yum: name={{ package }} state=present
