---
- name: Read the saved lsblk data
  hosts: localhost
  connection: local
  
  vars:
  - manageiq_validate_certs: false
  - auto_commit: true
  
  roles:
  - syncrou.manageiq-automate

  tasks:
  - name: Connect to workspace using token
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.automate_workspace }}"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: output
    
  roles:
  - ansible-role-listvars

  tasks:
  - name: Retrieve the saved 'date_stamp' state var
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_state_var:
        attribute: "lsblk_output"
    register: saved_lsblk_output
        
  - debug: var=saved_lsblk_output